### ISSUE TITLE
Warning when compiling: implicit declaration of ewah_add

### ISSUE THREAD

**Issue by fsolleza** [vmg/libewok#2]
When compiling and linking bitmap.c, I get an implicit declaration warning for ewah_add. It is implemented in ewah_bitmap.c but not declared in the ewok.h or ewok_rlw.h files. Easy fix would be to declare it in either file (probably the earlier as opposed to the latter).

Am I missing something?

**Comment by vmg** [comment]
No, not really. The code in this repository is sadly not up to date. I'd encourage you to check instead the vendored library in `git` (https://github.com/git/git/tree/master/ewah), which contains that fix and several other important ones.

Thanks!

**Comment by fsolleza** [comment]
Aha! Thanks
